services:
  turtlesim:
    build:
      context: ./docker
      dockerfile: Dockerfile.turtlesim
    container_name: ros2-turtlesim
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DISTRO=humble
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./docker/scripts:/ros2_ws/scripts:ro
    network_mode: host
    stdin_open: true
    tty: true
    command: bash -c "/ros2_ws/scripts/launch_turtlesim.sh"
